// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatrimonyBank.Data;

namespace PatrimonyBank.Migrations
{
    [DbContext(typeof(PatrimonyContext))]
    [Migration("20211022161222_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PatrimonyBank.Models.PessoaFisica", b =>
                {
                    b.Property<int>("PersonalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfoAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfoPhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalInfoPhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaCodePhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaCodePhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckDigit")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("CivilName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CivilNameFiliation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCallingCode1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCallingCode2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountrySubDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasBrazilianNationality")
                        .HasColumnType("bit");

                    b.Property<string>("IbgeTownCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaritalStatusAdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberPhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberPhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherNationalitiesInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneExtension1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneExtension2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialNameFiliation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TownName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeAdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeFiliation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypePhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypePhone2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonalID");

                    b.ToTable("PessoaFisica");
                });

            modelBuilder.Entity("PatrimonyBank.Models.PessoaJuridica", b =>
                {
                    b.Property<int>("IdPessoaJuridica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressAdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressCountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressCountrySubDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressDistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressGeographicCoordinatesLatitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressGeographicCoordinatesLongitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressIbgeTownCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressPostCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressTownName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnpjNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCnpjNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DocumentIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IncorporationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtherDocumentCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherDocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherDocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartieAdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartieCivilName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartieDocumentCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PartieDocumentExpirationOnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartieDocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartieDocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PartieShareHolding")
                        .HasColumnType("float");

                    b.Property<string>("PartieSocialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartieTradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartieType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartiesPersonType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhonesAdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhonesAreaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhonesCountryCallingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhonesExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhonesNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhonesType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPessoaJuridica");

                    b.ToTable("PessoaJuridica");
                });

            modelBuilder.Entity("PatrimonyBank.ViewMoldels.AccountPFVm", b =>
                {
                    b.Property<int>("personalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("additionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("additionalInfoAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("additionalInfoPhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("additionalInfoPhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("areaCodePhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("areaCodePhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("checkDigit")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("civilName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("civilNameFiliation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyCnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countryAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countryCallingCode1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countryCallingCode2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("countrySubDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("districtName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("expirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("hasBrazilianNationality")
                        .HasColumnType("bit");

                    b.Property<string>("ibgeTownCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("issueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("maritalStatusAdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maritalStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberPhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numberPhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("otherNationalitiesInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneExtension1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneExtension2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("socialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("socialNameFiliation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("townName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeAdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeFiliation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typePhone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typePhone2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("personalID");

                    b.ToTable("AccountPFVm");
                });
#pragma warning restore 612, 618
        }
    }
}
